language: python

python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI
  - "nightly"  # nightly build

virtualenv:
    system_site_packages: true

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

# command to run tests
script:
  - cd docs
  - make html
