language: python
python:
#- '2.7'
- '3.6'
install:
- pip install --upgrade pip
- pip install -U Sphinx
- pip install sphinx_rtd_theme
script:
- git clone https://github.com/DigiKlausur/digiklausur.github.io
- cd docs
- make html
- cd build
- rsync -a html/ ../../digiklausur.github.io
- cd ../../digiklausur.github.io
- git checkout -b develop
- git fetch --all
- git reset --hard origin/develop
- git add .
- git commit -m "New release pushed"
- git remote add origin-pages https://${GITHUBH_TOKEN}@github.com/DigiKlausur/digiklausur.github.io > /dev/null 2>&1
- git push --quiet --set-upstream origin-pages develop


env:
  global:
    secure: ZttBzX8oLsVxPEKpwK7nmrAEfZqo77j1plXSHSUyn/ovEDlyn62pJvOXtlTiiWOST8kKArXytOGlZdKfbN5dtNecy2AVIHTcOI1UiS60uqbkGh6bvMS56nWTBpZLOkgTepNeNrlII+w3koSONc3i+txHr4/KVIXmfNdForHRHwojSDLWeRYNiZ9AfWAB37q23eMtSLIiPqi0FBa+fCUADtXeN95HPHicfJ6GSFeN0L4JLGAmJnPyjUhFrGu7YhE2fHLIeMWhNidE52WBCnZdxekGfJDX0hX0y22lPvY4YqtcugnkF4ZnyAS04W5pukYwdimxm+eIXThZXG0Rcee0bnusa/T9ciWBuTIlfaD9DayjNRNdjS68CzNIvc0jvh19DWwrYC8y7p+IWftOU0NrECFwqV1StgREWtsysEyw0PjN1iWNLIyXZW0hJFXFWppm4maOKSUb6fYBpVG5JPmxKVE0msAGbRXozp9mNsh0dzJPSIgb1mdfSi9bVJBcCkmmz6lnDHr9/ApPlOYoOL7/2t0gYMluCq+m2m4c6aKO4dNecl644GvWbXmY88U/Z2I7JLR19UsFrhdY7CnjhxhpBM19Qv3YvGOZc8RP4OEl6/oODSqtybs9soOyvRecpmXTvmkLBTgpAEpIY0ryJWGIkhfTp4TCLlCF6GK+UVIsNPA=
