language: python
python:
#- '2.7'
- '3.6'

install:
- pip install --upgrade pip
- pip install -U Sphinx
- pip install sphinx_rtd_theme

script:
- cd docs
- make html
- git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/DigiKlausur/digiklausur.github.io.git
- rsync -a build/html/ digiklausur.github.io
- cd digiklausur.github.io
- git checkout -b develop
- git fetch --all
- git reset --hard origin/develop
- git add *
- git commit -m "New release pushed"
- git push origin develop


