language: python

python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI


#virtualenv:
#    system_site_packages: true

install:
  - pip install --upgrade pip
  - pip install -U Sphinx
  - pip install sphinx_rtd_theme
# command to run tests
script:
  - cd docs
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: develop
