---
name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: "0 1 * * 0" # at 01.00 week 0 ( every Sunday)

jobs:
  setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        pip install --upgrade pip
        pip install -r requirement.txt

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request') || (github.event_name == 'push' && github.ref == 'refs/heads/dev') 

    steps:
    - uses: actions/checkout@v2

    - name: Build E2x Docs
      run: |
        cd docs
        make html
        REV_VERSION=$(git rev-parse --short HEAD)

  deploy:
    name: Deploy E2x Docs
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy image
      shell: bash
      env:
        USERNAME: ${{ secrets.GH_USERNAME }}
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git clone https://$USERNAME:$TOKEN@github.com/DigiKlausur/digiklausur.github.io.git
        rm -rfv digiklausur.github.io/*
        rsync -a build/html/ digiklausur.github.io
        cd digiklausur.github.io
        if [[ -z `git diff --exit-code` ]]; then echo "No changes to push; exiting..."; exit 0; fi
        git add .
        git commit -m "New release $REV_VERSION pushed"
        git push origin master

